package lib

var varNames = [64]string{
	"INDEX",
	"&UNITS", // SCN_UNI
	"&SCRN",  // CRUSADE_MAP
	"&TXT",   // SCN_TER ?
	"&TABLE", // GENERIC_DTA
	"&S_TABLE", // SCN_DTA
	"INDEX2",
	"WHO",
	"&GENS",  // HEXES_DTA (-256)
	"MSG",
	"&LOC",
	"&UNIT",
	"NEXT",
	"ARG1",
	"ARG2",
	"DX",
	"DY",
	"&T_TABLE", // SCN_DTA_STRING
	"MVADD",
	"SX",
	"SY",
	"RANGE",
	"&SCORE", // 29927
	"WEATHER",
	"&STRAT", // SCN_TER_2
	"UPDATE",
	"MODE",
	"SCROL",
	"&DEFEN",
	"TEMP2",
	"TEMP",
	"AUTO",  // V10[8]
	"UNIT.STATE",
	"UNIT.PX",
	"UNIT.PY",
	"UNIT.MEN",
	"UNIT.TANKS",
	"UNIT.FORMATION",
	"UNIT.FATIGUE",
	"UNIT.TYPE",
	"UNIT.DESIGN",
	"UNIT.ORDER",
	"UNIT.GENERAL",
	"UNIT.OBJ_X",
	"UNIT.OBJ_Y",
	"UNIT.TERRAIN",
	"UNIT.SUPPLY",
	"UNIT.MORALE",
	"UNIT2.STATE",
	"UNIT2.PX",
	"UNIT2.PY",
	"UNIT2.MEN",
	"UNIT2.TANKS",
	"UNIT2.FORMATION",
	"UNIT2.FATIGUE",
	"UNIT2.TYPE",
	"UNIT2.DESIGN",
	"UNIT2.ORDER",
	"UNIT2.GENERAL",
	"UNIT2.OBJ_X",
	"UNIT2.OBJ_Y",
	"UNIT2.TERRAIN",
	"UNIT2.SUPPLY",
	"UNIT2.MORALE"}
