name: Static analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    
    - name: Install analysis tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Vet
      run: go vet ./...

    - name: Goimports
      run: test -z "$(goimports -e -d . | tee /dev/stderr)"

    - name: Staticcheck
      run: staticcheck ./...
